spring.datasource.url=jdbc:postgresql://localhost:5432/g62_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.schema=public
spring.datasource.driver=org.postgresql.Driver